/**
 * Render.com provider (self-host, guided).
 *
 * Render's Blueprint deploy (root render.yaml) is dashboard-driven, so this
 * provider is almost entirely a guided checklist sourced from
 * docs/deployment/RENDER.md. SESSION_SECRET / ENCRYPTION_SECRET are
 * auto-generated by Render during the Blueprint apply.
 */

import { z } from 'zod';
import type { DeployProvider, ExecContext, LogLine, Step } from '../types.js';
import { emitManual } from '../manual.js';

const inputSchema = z.object({});

async function checkPrereqs() {
  // Render is entirely dashboard/Git-driven — no local tooling required.
  return [];
}

function plan(): Step[] {
  return [
    {
      id: 'blueprint',
      title: 'Apply the Render Blueprint',
      kind: 'manual',
      instructions:
        'Render reads the repo root render.yaml and creates both services automatically.',
      commands: [
        '1. Go to https://render.com/deploy and connect your GitHub repo',
        '2. Render detects render.yaml and shows the Blueprint preview',
        '3. Review the services, then click "Apply"',
      ],
    },
    {
      id: 'env',
      title: 'Set the sync:false environment variables',
      kind: 'manual',
      instructions:
        'After creation, open each service\'s Environment tab and set the secret vars.\n' +
        'CORS_ORIGIN and AGENT_SERVER_URL must be full https:// URLs.',
      commands: [
        '# Backend (achilles-backend):',
        'CLERK_PUBLISHABLE_KEY=pk_live_...',
        'CLERK_SECRET_KEY=sk_live_...',
        'CORS_ORIGIN=https://<your-frontend>.onrender.com',
        'AGENT_SERVER_URL=https://<your-backend>.onrender.com',
        'TESTS_REPO_URL=https://github.com/your-org/f0_library.git',
        'AGENT_REPO_URL=https://github.com/your-org/ProjectAchilles.git',
        'GITHUB_TOKEN=ghp_...',
        'ELASTICSEARCH_CLOUD_ID=<from Elastic Cloud console>',
        'ELASTICSEARCH_API_KEY=<from Elastic Cloud console>',
        '',
        '# Frontend (achilles-frontend):',
        'CLERK_PUBLISHABLE_KEY=pk_live_...',
        'VITE_API_URL=https://<your-backend>.onrender.com',
      ],
    },
    {
      id: 'deploy',
      title: 'Trigger a manual deploy on both services',
      kind: 'manual',
      instructions:
        'Trigger a deploy on both services (or push a commit). SESSION_SECRET and\n' +
        'ENCRYPTION_SECRET are auto-generated by Render — do not override them.',
    },
    {
      id: 'verify',
      title: 'Verify',
      kind: 'manual',
      instructions: 'Confirm the backend health endpoint and the frontend sign-in page.',
      commands: ['curl https://<your-backend>.onrender.com/api/health'],
    },
  ];
}

async function* execute(step: Step, _ctx: ExecContext): AsyncIterable<LogLine> {
  yield* emitManual(step);
}

export const renderProvider: DeployProvider = {
  id: 'render',
  label: 'Render.com',
  summary: 'Blueprint deploy from render.yaml. Guided: dashboard + env vars',
  modes: ['self-host'],
  automation: 'guided',
  checkPrereqs,
  inputSchema: () => inputSchema,
  plan,
  execute,
};
