/**
 * Writes `deploy.config.env` from validated wizard inputs.
 *
 * The three Caddy single-origin installers (`deploy-server.sh`,
 * `deploy-remote.sh`, `deploy-do.sh`) all source this file with
 * `set -a; . deploy.config.env; set +a`, so a flat KEY=value file is all they
 * need. Blank secrets are intentionally left blank — the scripts auto-generate
 * `SESSION_SECRET` / `ENCRYPTION_SECRET` / `CLI_AUTH_SECRET` themselves.
 *
 * Secrets are written to disk at mode 0600 and never echoed to the log pane.
 */

import { writeFileSync } from 'fs';
import { join } from 'path';

/** Keys we know how to emit, in file order. Mirrors deploy.config.env.example. */
const KEY_ORDER = [
  'ACHILLES_DOMAIN',
  'ACME_EMAIL',
  'TLS_MODE',
  'CADDY_DNS_PROVIDER',
  'CADDY_DNS_MODULE',
  'CADDY_DNS_TOKEN',
  'CLERK_PUBLISHABLE_KEY',
  'CLERK_SECRET_KEY',
  'SESSION_SECRET',
  'ENCRYPTION_SECRET',
  'CLI_AUTH_SECRET',
  'ES_MODE',
  'ELASTICSEARCH_CLOUD_ID',
  'ELASTICSEARCH_API_KEY',
  'ELASTICSEARCH_INDEX_PATTERN',
  'SEED_ES',
  'TESTS_REPO_URL',
  'TESTS_REPO_BRANCH',
  'AGENT_REPO_URL',
  'AGENT_REPO_BRANCH',
  'GITHUB_TOKEN',
  'DO_API_TOKEN',
  'DO_REGION',
  'DO_SIZE',
  'DO_IMAGE',
  'DO_DROPLET_NAME',
  'DO_SSH_KEY_FINGERPRINT',
  'DO_MANAGE_DNS',
  'SSH_USER',
  'SSH_HOST',
  'SSH_PORT',
  'REMOTE_DIR',
] as const;

export type ConfigKey = (typeof KEY_ORDER)[number];

const HEADER = `# =============================================================================
# ProjectAchilles — server deployment config
# Generated by \`achilles deploy\`. Contains secrets — do not commit (gitignored).
# Blank secret values are auto-generated by the deploy script on first run.
# =============================================================================
`;

/** Render the config file body from a value map (omitting undefined values). */
export function renderConfig(values: Partial<Record<ConfigKey, string>>): string {
  const lines: string[] = [HEADER];
  for (const key of KEY_ORDER) {
    const value = values[key];
    if (value === undefined) continue;
    lines.push(`${key}=${value}`);
  }
  return lines.join('\n') + '\n';
}

/**
 * Write `deploy.config.env` into `dir` (defaults to repo root) at mode 0600.
 * Returns the absolute path written.
 */
export function writeConfig(
  dir: string,
  values: Partial<Record<ConfigKey, string>>,
): string {
  const path = join(dir, 'deploy.config.env');
  writeFileSync(path, renderConfig(values), { mode: 0o600 });
  return path;
}
