name: Blog

on:
  push:
    branches: [main]
    paths: ['blog/**']
  pull_request:
    branches: [main]
    paths: ['blog/**']

jobs:
  build:
    name: Blog
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: blog
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: blog/package-lock.json
      - run: npm ci
      - run: npm test
      - run: npm run build
